### ISSUE TITLE
Channel "Random" seems to not working

### ISSUE THREAD

**Issue by hug33k** [5punk/react-slack-chat#10]
I added the channel _random_ on the `channelId` list but it throws an error :

<img width="1157" alt="capture d ecran 2017-02-22 a 15 40 47" src="https://cloud.githubusercontent.com/assets/1793678/23203540/810e1c44-f915-11e6-8264-28cbd207f1b8.png">

Is this channel working with this component for your case ?

**Comment by 5punk** [comment]
@hug33k 
The `channelId` is a unique ID for every channel handed out by Slack.

It is **NOT** the title / name of the channel.

The best way to get the Channel ID is to right click on some link related to it and copy the URL link.
They usually look something like this: "`C1CSMYV9`"

**Comment by 5punk** [comment]
I usually get the channelIDs by copying the "Add an app or integration" link.

![image](https://cloud.githubusercontent.com/assets/8335261/23204551/e307107e-f89b-11e6-8fb9-0a3a273c3ae9.png)

**Comment by hug33k** [comment]
I know, I added the channel ID and not the name ;)

**Comment by 5punk** [comment]
@hug33k 
Share your code snippet for including the component?

**Comment by hug33k** [comment]
```js
import React, { Component } from 'react';
import { ReactSlackChat } from 'react-slack-chat';

class MyComponent extends Component {
	render() {
		return (
			<div id="mycomponent">
					<ReactSlackChat
						botName='ReactBot'
						apiToken='$API_TOKEN'
						channelId={[
							'$CHANNEL_ID_GENERAL',
							'$CHANNEL_ID_RANDOM',
							'$CHANNEL_ID_OTHER'
						]}
						userImage='$IMG_LOGO'
						debugMode={true}
						hooks={[]}
					/>
					{this.props.children}
				</div>
			</div>
		);
	}
}

export default MyComponent;
```

**Comment by 5punk** [comment]
![image](https://cloud.githubusercontent.com/assets/8335261/23205363/7640ac18-f89e-11e6-9ce2-2861ce58d8bb.png)


---
I am pushing a new version in a few minutes that allows you to specify `channelNames` instead.
Does that sound like something that would be more convenient?

```
<ReactSlackChat
      botName='5punk-bottt'
      apiToken='xoxb-111120916065-BLAH'
      channelNames={['random', 'test', 'test22']} // THIS
      helpText='Need Help?'
      debugMode={true}
      userImage='http://www.iconshock.com/img_vista/FLAT/mail/jpg/robot_icon.jpg'
      hooks={[
        {
          /* My Custom Hook */
          id: 'getSystemInfo',
          action: () => 'MY SYSTEM INFO!'
        }
      ]}
    />
```

**Comment by hug33k** [comment]
Using name or id isn't a problem for me (I actually use IDs).

The problem is, when I select _random_ on the list, I have the error showed on the first message.

**Comment by 5punk** [comment]
I tried it with the IDs too.
Could it be that your `random` channel is private?

There are instances where `general` and `random` channels are private.

**Comment by 5punk** [comment]
Would you like to try it with `channelNames` instead?
I can publish the latest right away.

**Comment by hug33k** [comment]
No, `random` is public on my Slack. I also added my bot to the members of this channel, just in case, but still not working.
If you think it can fix the problem, why not trying? :)

**Comment by 5punk** [comment]
`react-slack-chat@v1.4.0` is out.

Uses `channelNames` instead of channelIds.

Please try it, hopefully it picks "random" up.

**Comment by hug33k** [comment]
Still have the issue, even with `channelNames` :(

**Comment by 5punk** [comment]
Can you post the screenshot?
The error cannot be `indexOf` anymore.

**Comment by hug33k** [comment]
Unfortunately, it is `indexOf` again...
<img width="1163" alt="capture d ecran 2017-02-22 a 16 44 31" src="https://cloud.githubusercontent.com/assets/1793678/23205937/61769aba-f91e-11e6-84c9-00f87631ad84.png">

**Comment by 5punk** [comment]
I just changed the code to use `includes()` instead.
https://github.com/5punk/react-slack-chat/blob/master/src/ReactSlackChat.js#L213

Can you confirm you've installed `react-slack-chat@v1.4.0`?

**Comment by hug33k** [comment]
Sir, yes sir! :)

**Comment by 5punk** [comment]
That is so bizarre.....

Well, `random` works for 2 other test Slack Teams I've created.
I am going to ask someone else to confirm.

In the meantime, I can only suggest that you don't use `random`. 😕

**Comment by hug33k** [comment]
Yes, it is so weird...
I will find a way to not use `random` ;)

**Comment by 5punk** [comment]
Sorry, I know this is not a solution.

If you don't have any private messages on it, I can take a look at the response you get from the network tab.
A call is made to the endpoint `channels.history`.

If you dump the response of that call here, I can parse the data and simulate it on my end to see where the problem lies.
