### ISSUE TITLE
Manually select icon for channels

### ISSUE THREAD

**Issue by hug33k** [5punk/react-slack-chat#11]
Is it possible to add an option to manually select icon for channels ?

- Idea 1 : Add a property `channelsIcon` to `ReactSlackChat`
- Idea 2 : Use an object list for channelId like this

```js
<ReactSlackChat

	[...]

	channelId={[
		{
			"channel": "General",
			"id": "XXXXXXXXX",
			"icon": "IMAGE_URL"
		}
	]}

	[...]

/>
```

**Comment by 5punk** [comment]
@Jflinchum 
Can you look into this?

**Comment by 5punk** [comment]
@Jflinchum added https://github.com/5punk/react-slack-chat/pull/12

@hug33k Sit tight!

**Comment by 5punk** [comment]
@hug33k `react-slack-chat@v1.5.0` has the feature you requested. Refer to the documentation for usage.

Enjoy and thanks for using.
Feel free to stop by and have a chat with us again.
