### ISSUE TITLE
Channels not displaying

### ISSUE THREAD

**Issue by YonM** [5punk/react-slack-chat#13]
Hi, I'm new with this and Slack. So I'm not sure if the issue stems from Slack or not.

Following the [link ](https://api.slack.com/bot-users)in the prerequisites. I then click the link on the resulting page where it says: [creating a new bot user](https://my.slack.com/services/new/bot)

I make the bot join a channel. I then take the token, the name of the bot and the channel and insert into the props of the ReactSlackChat component. The widget appears but no channel is displayed. It's simply an empty white widget with a blue header bar. Is this the correct usage?

**Comment by 5punk** [comment]
@YonM Can you enable debug mode and check your logs?
Pass `debugMode={true}` as a prop.

There's a high chance, that you're getting 401'd

Check your network tab to see what the response from slack calls are.

**Comment by YonM** [comment]
Checking the console I get 2 errors/warnings.

Warning: Failed prop type: The prop `channelNames` is marked as required in `t`, but its value is `undefined` >> warning.js:36

Uncaught TypeError: Cannot read property 'includes' of undefined react-slack-chat.js:2

**Comment by YonM** [comment]
Ah, so I found out that the README.md is out of date or something. I simply passed an array of channelNames (strings) and it works.

**Comment by 5punk** [comment]
@YonM Guess you figured it out.
Let me know if I can help you in any way :)
