### ISSUE TITLE
Is that possible to create a new session for different chat?

### ISSUE THREAD

**Issue by LeonAppDev** [5punk/react-slack-chat#17]
I want to create a customer service chat box based on your component. But for now, anyone enters into the channel random could see the message typed in before, so is that possible for every different user to create a different session and everyone could only see their type in.

**Comment by 5punk** [comment]
No, that is not possible for a server-less slack chat application.

It would lead to many complex edge case scenarios, that would breathe life into a nightmare of bugs.
I don't plan to support that anytime in the future.

This widget was meant to be a non-authed, open community, chat plugin.
