### ISSUE TITLE
support chat, default channel, user/thread filter

### ISSUE THREAD

**Issue by yekibud** [5punk/react-slack-chat#18]
Hi.

Thanks for the great project!  I forked and added some features/props to enable support chat functionality.  Here's [the diff](https://github.com/5punk/react-slack-chat/compare/master...yekibud:add-support-channel).

By specifying a `defaultChannel` and filtering by the conversation identified by the last thread of the username/IP you can receive user chats into a single support channel and reply to users in threads.  The message filtering makes it so users don't see other user comments and the threaded conversations on the Slack side helps keep communication organized.

Might not be totally robust, but I think it does the basic job and adds a handy optional use-case/feature to the project.  Let me know what you think and if you want me to submit a pull request.

Feedback or suggestions on my React code are very welcome since this is my first time doing anything in React.

**Comment by 5punk** [comment]
Great job on the PR, I love it.
There were some minor errors in the use case where the `userMessages` are empty (first time use case/user never posted), it can be solved by this snippet below.

```
          if (this.props.filterByLastUserThread) {
            const userMessages = that.messages.filter((message) => message.username === this.props.botName);
            if (userMessages.length > 0) {
              that.lastThreadTs = userMessages.slice(-1)[0].thread_ts;
              that.messages = that.messages.filter((message) => message.username === this.props.botName || message.thread_ts === that.lastThreadTs);
            } else {
              that.messages = [];
            }
          }
```
To be honest `userMessages.slice(-1)[0].thread_ts;` this makes me a little nervous, I would like intent to be declared in code expressly as opposed to `[randomNumbers]` it's hard for readability. It's fine if you can't figure out a way around this.

I would like the prop `filterByLastUserThread` to be named to `singleUserMode` instead.

As a last request, if you could sprinkle your code with comments/documentation that would be awesome.

Thank you so much for the contribution, this was a much-needed feature by the community,

**Comment by yekibud** [comment]
Sweet!  Your suggestions make sense.  Thanks for the review.  I'll make changes tomorrow and send the PR.

**Comment by 5punk** [comment]
@yekibud
Great job on this.
Could you update the documentation in the read me?
Thank you

**Comment by yekibud** [comment]
Thanks!  Will do.  Also, I think you need to update the dist in your repo - but, again, I'm not sure why that's there.

**Comment by 5punk** [comment]
`1.8.3` has your features in it.
Removed dist (legacy method)

Thanks again.
