### ISSUE TITLE
<--react-empty--> on deploy

### ISSUE THREAD

**Issue by absinto** [5punk/react-slack-chat#26]
The component works fine when testing it locally but when I try to deploy it in homolog environment it doesn't work. I get this comment <--react-empty--> where the component is supposed to be. 
![screen shot 2018-03-02 at 12 43 04](https://user-images.githubusercontent.com/9686473/36907402-51173c8c-1e17-11e8-852b-a797a4048047.png)

When trying to deploy the other warnings I get on this package are:
![screen shot 2018-03-02 at 12 49 01](https://user-images.githubusercontent.com/9686473/36907756-294206be-1e18-11e8-8957-820640f6d685.png)

I see our react versions aren't compatible but I can't seem to update

**Comment by 5punk** [comment]
I believe this should be fixed by the new bump to `React 16.8`
