### ISSUE TITLE
Parameters to be passed in the 'channels' object attribute

### ISSUE THREAD

**Issue by singhrohan62** [5punk/react-slack-chat#30]
@5punk could you please help me in solving one of my doubts? I will be very thankful to you.
Here it goes : In the `<ReactSlackChat>` Component, we pass the channel attribute and in that object, we pass name, id etc. What if a real slack channel exists and I want to add in the component, I think that we could pass name of the channel in name key, but what to pass in 'id' key? Kindly reply ASAP
Thank you!

**Comment by 5punk** [comment]
@singhrohan62 
If you refer the [example usage](https://github.com/5punk/react-slack-chat#example-usage)
You will observe that the `id` attribute in the channels object is not mandatory.

**Comment by 5punk** [comment]
Let me know if that works for you.

**Comment by singhrohan62** [comment]
Yes I figured that out yesterday 😅 , however, if there could be a way where messages are retrieve from the channel and one more thing...we are declaring a bot name in the `ReactSlackChat`
component, and in the slack channel we see that the message is sent by the same bot as provided in the component, if there is a way where we can display the name of the user instead of the bot? Like real user instead of bot?I thought that we could use Slack API for retrieving messages, but is there any another way you could tell? If possible, do tell me @5punk 😅 
Thank you

**Comment by 5punk** [comment]
Sure you can.

`botName='5punk-unique-id' // VisitorID, CorpID, Email, IP address etc.`

You can set botName to be anything you wish, it is highly encouraged to set it to something unique per visitor.

**Comment by singhrohan62** [comment]
> You can set botName to be anything you wish, it is highly encouraged to set it to something unique per visitor.
@5punk I think I couldn't express my doubt precisely. So I request kindly have a look on one of the scenarios that I present here:

Lets assume I have email-ID of a person of 'X' (be 'abc@d.com')  who is also member of the channel that I provide in the component attribute. I want that whatever message I send through my localhost application, in Slack, it should display that "X sent that message" instead of "abc@d.com BOT sent that message". I added screenshot so that you could understand my doubt more precisely.

![screenshot 73](https://user-images.githubusercontent.com/28647524/47453138-8f84d880-d7e9-11e8-9fda-62735849f212.png)

Here, I am sending message to channel "testing_slack"

![screenshot 74](https://user-images.githubusercontent.com/28647524/47453255-e8ed0780-d7e9-11e8-9fee-455cafa465a2.png)

Now, is there any way that instead of displaying that bot named "slack_integration_bot" sent the message, it should display that "Rohan" (since I know my email-ID) sent that message? I know I am asking a lot from you but can you help me in finding the way for accomplishing this task?
Thanking You.

**Comment by 5punk** [comment]
It will use the name of the bot. In your case: `abc@d.com`.

It will always look something like this:
![image](https://user-images.githubusercontent.com/8335261/47453642-1b631a00-d782-11e8-9f19-ab24cf6c574f.png)

If slack allowed bots to post as regular users that would be a serious security flaw. Masquerading as other users would become really easy.

**Comment by singhrohan62** [comment]
@5punk one more question, what does the attribute `defaultMessage` require in the fields? I tried string and object, however it is not working. Kindly reply ASAP
Thanks!
