### ISSUE TITLE
Integration with Gatstby : window is not defined

### ISSUE THREAD

**Issue by iamskar** [5punk/react-slack-chat#32]
This errors when using with Gatsby - when building -Gatsby build  i get an error `WebpackError: ReferenceError: window is not defined`.

Can you please suggest how this can be fixed.

**Comment by marcelharinck** [comment]
I have this issue as well :(

**Comment by jackywxd** [comment]
Error: "WebpackError: ReferenceError: window is not defined" is a common error in Gatsby. It is not related to this project. You can search Gatsby official website and get some suggestions how to fix this type of problem.

**Comment by 5punk** [comment]
Thank you @jackywxd
