### ISSUE TITLE
User names displayed as UIDs

### ISSUE THREAD

**Issue by jwhiteaei** [5punk/react-slack-chat#35]
When opening a new chat window, users are displayed as their underlying UIDs, for example: **<@UL18X8B8V>** has joined the channel.

**Comment by 5punk** [comment]
Do you mean the administrators?

**Comment by jwhiteaei** [comment]
Yes. I am using the slack web API to invite/kick users from a channel based upon which laptops are on location. The company I work for has ~70 laptops that rotate through ~35 locations. Here is a screenshot. The users are named "Laptop 006" and "Laptop 001" but they show up as <@UKT1AS1J7> and <@UL62AM2H4> respectively.  Please see screenshot.

![image](https://user-images.githubusercontent.com/42450757/61139279-a4e08680-a48e-11e9-9dcb-acd8acb3da81.png)

**Comment by 5punk** [comment]
Unfortunately, the slack response doesn't reveal the actual admin name.

I've screenshot-ed the network response to the get chat history network endpoint from the slack npm library.
![image](https://user-images.githubusercontent.com/8335261/83959360-16f15500-a831-11ea-8f38-24d2f1edbfb4.png)

It's something I'd love to add to the widget myself, but can't with the current limitation.
