### ISSUE TITLE
ReferenceError: window is not defined - next.js Server side Rendering

### ISSUE THREAD

**Issue by mizzb** [5punk/react-slack-chat#39]
I am getting ReferenceError: window is not defined error, using nextjs for SSR 
________________________________________________________________
(anonymous function)
/Users/mishabmusthafa/workspace/infin-ai/infin-ai/node_modules/react-slack-chat/dist/react-slack-chat.js:1:372
Module._compile
internal/modules/cjs/loader.js:778:30
Module._extensions..js
internal/modules/cjs/loader.js:789:10
Module.load
internal/modules/cjs/loader.js:653:32
tryModuleLoad
internal/modules/cjs/loader.js:593:12
Function.Module._load
internal/modules/cjs/loader.js:585:3
Module.require
internal/modules/cjs/loader.js:692:17
require
internal/modules/cjs/helpers.js:25:18
react-slack-chat
webpack:/external "react-slack-chat":1
> 1 | module.exports = require("react-slack-chat");

**Comment by 5punk** [comment]
You might need to stub out window to use front end libraries in SSR like [so](https://github.com/hellosign/hellosign-embedded/issues/107#issuecomment-467981230)
