### ISSUE TITLE
Super expression must either be null or a function

### ISSUE THREAD

**Issue by thvardhan** [5punk/react-slack-chat#60]
**Describe the bug**
React slack chat crashes when loaded on nginx production built react web app.

**To Reproduce**
1. Import react slack chat
2. npm run build
3. copy built folder to ngnix... /var/www/html/ in ubuntu to deploy on nginx
4. open local host and see error in browser console

**Expected behavior**
Library loads without crashing

**Screenshots**
![WhatsApp Image 2021-06-11 at 11 30 10 PM](https://user-images.githubusercontent.com/17314986/121730593-861d1b80-cb0d-11eb-9abf-8baba935930f.jpeg)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18
 - Browser Chrome
 - Version 83

**Comment by rahulkhatry4** [comment]
Instead of importing from 'react-slack-chat';

import { ReactSlackChat } from 'react-slack-chat';

try importing from 'react-slack-chat/dist/react-slack-chat-with-default-hooks';

import { ReactSlackChat } from 'react-slack-chat/dist/react-slack-chat-with-default-hooks';

Solved it for us

**Comment by thvardhan** [comment]
Thanks! it solved it!
