### ISSUE TITLE
npm error when starting with your module

### ISSUE THREAD

**Issue by posix4e** [5punk/react-slack-chat#8]
I get
```
Warning in ./~/react-slack-chat/dist/react-slack-chat.js
Critical dependencies:
8:4488-4495 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/react-slack-chat/dist/react-slack-chat.js 8:4488-4495

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
```

**Comment by 5punk** [comment]
Oh.....
Let me have a look....

It seems more like a warning (Which I will fix)
But is it breaking?

**Comment by posix4e** [comment]
1.2.0. It seems broke

**Comment by 5punk** [comment]
@posix4e Gimme a few, I will have a fix end of the day.

**Comment by hug33k** [comment]
I don't know for you @posix4e but in addition to the warning, I have this error on my browser console :
<img width="845" alt="capture d ecran 2017-02-22 a 02 11 47" src="https://cloud.githubusercontent.com/assets/1793678/23180576/73a4bfb6-f8a4-11e6-9d9e-00a85b2b5940.png">
(`marquis.min.js`is my output from Webpack)

**Comment by 5punk** [comment]
@hug33k 
That doesn't seem related to this issue.

Either way it seems like you might not have `node v6+`
Highly recommend you upgrading to the latest node.

Try to polyfill babel, it's trying to access functions it expects to be there.
Source: [here](http://stackoverflow.com/questions/33527653/babel-6-regeneratorruntime-is-not-defined-with-async-await)

**Comment by 5punk** [comment]
@hug33k Come right back if it doesn't work or you need me.

**Comment by 5punk** [comment]
@posix4e 
It seems this is a arbitrary problem with the way webpack loads browserify like UMD built libraries.
It is [confirmed](https://github.com/webpack/webpack/issues/1617#issuecomment-181712333) to be a warning and not a problem or error.

You can proceed to add the `noParse` flag in your webpack if you want to avoid seeing such warnings. It has been selected as the [answer for this issue](https://github.com/webpack/webpack/issues/1617#issuecomment-223676403).

```
...
module: {
    noParse: /node_modules\/react-slack-chat\/dist\/react-slack-chat.js/,
    loaders: [{
      // Your loaders ...
    }]
}
...
```

I just cloned a new [react example repository](https://github.com/mzabriskie/react-example). Ran it locally and installed the latest `react-slack-chat@v1.3.0`.

It works beautifully out of the box, as expected.
![image](https://cloud.githubusercontent.com/assets/8335261/23193137/40b10512-f85c-11e6-9d5c-fdda5f11163d.png)


Please let me know if you need help in setting up your Slack bot.

**Comment by 5punk** [comment]
If you would like, please share your code. I can have a look at your code and help you set up the module, the right way.

**Comment by posix4e** [comment]
Kk I'll give it a shot close for now

**Comment by 5punk** [comment]
@posix4e Feel free to comment, if you still need help.

Right here to help.

**Comment by posix4e** [comment]
Thanks y'all
